### PR TITLE
bump version to 1.5.0

### PR DESCRIPTION
**Pull request by crwilcox**
## ⚠️ Breaking Change

The following breaking change to the beta endpoint is introduced in this release:

- `GoogleDataCollectionConfig` and `google_data_collection_opt_in` have been removed from `v1p1beta1`.

If your code does not use beta functionality (i.e. you never explicitly require `v1p1beta1`), your code will not require any changes.

---

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by alexander-fenster** [comment]
For version changes, could you also include the draft of release notes?

**Comment by crwilcox** [comment]
Sure. Also made a note of that in the release playbook so it gets done in the future for this.

**Comment by alexander-fenster** [comment]
Why was this incompatibility introduced? I understand it's beta, but the more incompatible things we merge, the more leaky is our semver model, and I hate that.  (@jonparrott to decide if it's OK in this case, but I hate it so much)

The correct way, as I see it, is to leave the field there until the next beta endpoint is available.

**Comment by jonparrott** [comment]
> Why was this incompatibility introduced?

The terse (and possibly unhelpful answer) is that they wanted to do so.

>  I understand it's beta, but the more incompatible things we merge, the more leaky is our semver model, and I hate that. (@jonparrott to decide if it's OK in this case, but I hate it so much)

Unfortunately there's not much we can do here. It's a beta endpoint, so I'm okay with this (as much as I can be okay with it).

**Comment by alexander-fenster** [comment]
I have updated release notes (some `formatting` and some extra words about beta).

**Pull request merged**
