### PR TITLE
docs: add additional context to samples

### PR DESCRIPTION
**Pull request by dev-slatto**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-speech/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Just som small examples on parameters in README.md to get developers up and running quicker, in addition to adding <storageUri> as parameter on transcribeContextClasses.js

### CODE REVIEW

**Comment by dev-slatto** [comment]
@googlebot I signed it!

**Review by JustinBeckwith — DISMISSED** [review]
Greetings, and thank you for the PR!  This file is entirely auto-generated based on the samples available in the `samples/` directory.  For usage information, it relies on this little bit of metadata that looks like this being in the same file as the sample:
```js
// sample-metadata:
//   title: List Assets
//   description: List assets under the current project.
//   usage: node listAssets <ASSET_TYPES>
//   example: node listAssets storage.googleapis.com/Bucket,bigquery.googleapis.com/Table"
```

You can see an example of it in action here:
https://github.com/googleapis/nodejs-asset/blob/master/samples/listAssets.js#L17

If you add this block (specifically the usage part) inside of the samples, a robot will come along and update this README :)

**Comment by dev-slatto** [comment]
Thank you for the quick response @JustinBeckwith ! Does this look ok?

**Comment by bcoe** [comment]
@JustinBeckwith @dev-slatto 👋 I don't think that `example` is a field we support today ([looking at the template](https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/node_library/samples/README.md)).

There's been discussion of moving away from comments for providing meta information, so I'm not sure that we want to add an additional field like this today.

@dev-slatto would you be okay with just adding the additional meta information for "Transcribe Context Classes"?

**Comment by dev-slatto** [comment]
@bcoe 👋🏼 Sure! I just found it helpful to get a jump start in projects with examples from other repos. 

Should be fixed in the latest commit - does that look okay?

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@dev-slatto this looks good to me, thank you for the contribution. @JustinBeckwith mind taking another look?

**Comment by dev-slatto** [comment]
@JustinBeckwith Is this PR still relevant or should I close this PR for now?

**Review by bcoe — APPROVED** [review]

**Review by bcoe — DISMISSED** [review]

**Review by bcoe — APPROVED** [review]

**Pull request merged**
