### PR TITLE
docs(samples): removing migrated samples

### PR DESCRIPTION
**Pull request by meredithslota**
Do not merge until SnippetBot is happy.

### CODE REVIEW

**Comment by meredithslota** [comment]
Sent cl/502075743 to update sample locations as samples have moved.

**Comment by meredithslota** [comment]
Submitted cl/502075743, now just waiting for the SnippetBot index to update with whether any remaining samples are linked in docs.

**Comment by meredithslota** [comment]
SnippetBot is now happy, removing the `do not merge` label. Samples test is still failing, will look into this.

**Comment by meredithslota** [comment]
Reverted changes to `quickstart.js` and testing as that is used by the library.

**Review by sofisl — APPROVED** [review]

**Pull request merged**
