### PR TITLE
chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by alexander-fenster** [comment]
Originally we test just one Node version in AppVeyor because it's terribly slow (compared to CircleCI). If the previous two PRs (#77 and especially #76) help make it faster we can try enabling Node10 for all our packages as well. Let's try anyway.

**Comment by DanielRuf** [comment]
We should at least keep an eye on the current stable release (10) as it produce(d) failing tests in other projects in Appveyor. So far it looks good.

**Comment by alexander-fenster** [comment]
We run the main testing on CircleCI (on all version from node4 to node10, node4 going to be removed soon). AppVeyor just runs some basic sanity testing. But I agree we can add node10 there as well. 

Also, just FYI, we try to keep the CI configuration changes between projects to minimum so I'll probably make the same change to AppVeyor config across all of our googleapis/nodejs-* packages.

**Comment by DanielRuf** [comment]
> Also, just FYI, we try to keep the CI configuration changes between projects to minimum so I'll probably make the same change to AppVeyor config across all of our googleapis/nodejs-* packages.

Sounds good, as Windows is a "bit" different and in many cases shows other issues than the Travis CI builds on the Linux / Ubuntu images.

**Pull request merged**
