### PR TITLE
fix(samples): end stream before destroying it

### PR DESCRIPTION
**Pull request by Wirnex**
I've been getting this error until I put call of end() for the stream before destroying it.
`API request error 14 UNAVAILABLE: 408:Request Timeout`

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-speech/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by Wirnex** [comment]
@googlebot I signed it!

**Comment by bcoe** [comment]
@Wirnex It's not immediately apparent to me why this would help suppress that error. @alexander-fenster can you shine any light on what might be happening here?

**Comment by alexander-fenster** [comment]
Let me see if I can reproduce the failure.

**Comment by alexander-fenster** [comment]
Thanks @Wirnex, and sorry for delay!

**Review by alexander-fenster — APPROVED** [review]

**Pull request merged**
