### PR TITLE
docs(samples): convert samples tests to use mocha

### PR DESCRIPTION
**Pull request by vijay-qlogic**
Fixes [nodejs-speeech: Convert all sample tests to mocha](https://github.com/googleapis/google-cloud-node/issues/2865) (it's a good idea to open an issue first for discussion)

- [ ] Tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Just a reminder to come back around and investigate the test failures :)

**Comment by vijay-qlogic** [comment]
Yes, I'm  looking into it.. Facing some challenges to resolve the issues here.

**Comment by JustinBeckwith** [comment]
Coo.  Let me know if I can help!

**Comment by vijay-qlogic** [comment]
One test "should run sync recognize with enhanced model" 
in file "samples/system-test/recognize.test.js" on line no.129 is failing.

To fix that we need to enable "data logging" for "Cloud Speech API" in our project "Grass Clump 479"

Here is link to enable that [Enable data logging](https://console.cloud.google.com/apis/api/speech.googleapis.com/data_logging?project=grass-clump-479)

I do not have enough permissions to do so

**Comment by JustinBeckwith** [comment]
👋 the test failure looks unrelated to that though:

```
 1) BetaFeatures
       should run speech diarization on a local file:
      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual
      -false
      +true
      at Context.it (system-test/betaFeatures.test.js:58:12)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Pull request merged**
