### PR TITLE
Release @google-cloud/speech v2.1.1

### LINKED ISSUE #194: DeprecationWarning: grpc.load
#### Environment details
  - macOS Mojave
  - Node.js `v10.11.0`
  - npm `6.4.1`
  - `@google-cloud/speech` version `2.1.0`

#### Steps to reproduce

Launching any of the samples from this repo emits a deprecation warning:

```
(node:13129) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
```

Source code: https://github.com/grpc/grpc-node/commit/efa3d430ddf3f5e3f8b47d6ece4b3ce058e88834

I'm guessing one of this repo's deps is stale, maybe google-gax.

Thanks in advance

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This pull request was generated using releasetool.

Resolves #194

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Note to reviewers - samples tests are green on Circle 🤷‍♂️ 

image

**Comment by JustinBeckwith** [comment]
CR = @crwilcox

**Comment by JustinBeckwith** [comment]
Release is at https://github.com/googleapis/nodejs-speech/releases/tag/v2.1.1

**Comment by julien-c** [comment]
Do you mind pushing to `npm` (or is it automatic?)

**Comment by JustinBeckwith** [comment]
Should be automatic :)

**Comment by julien-c** [comment]
not yet: https://www.npmjs.com/package/@google-cloud/speech

**Comment by JustinBeckwith** [comment]
Heh, yeah, something went wrong.  Will debug soon :)

**Pull request merged**
